defmodule CovenantAI.Repo.Migrations.AddAccessRequestResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :full_name, :text, null: false
      add :email, :text, null: false
      add :phone, :text, null: false
      add :hoa_name, :text, null: false
      add :hoa_address, :map, null: false
      add :estimated_units, :bigint
      add :website, :text
      add :role_in_hoa, :text, null: false
      add :how_found_us, :text
      add :status, :text, null: false, default: "pending"
      add :reviewed_at, :utc_datetime_usec
      add :internal_notes, :text

      add :reviewed_by_id,
          references(:users,
            column: :id,
            name: "access_requests_reviewed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:access_requests, [:email], name: "access_requests_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:access_requests, [:email],
                     name: "access_requests_unique_email_index"
                   )

    drop constraint(:access_requests, "access_requests_reviewed_by_id_fkey")

    drop table(:access_requests)
  end
end
