defmodule CovenantAI.Repo.Migrations.AddCoreResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :role, :text
      add :community_id, :uuid
    end

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:community_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :document_type, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :file_path, :text, null: false
      add :file_name, :text, null: false
      add :community_id, :uuid, null: false
      add :uploaded_by_id, :uuid, null: false
    end

    create table(:communities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:users) do
      modify :community_id,
             references(:communities,
               column: :id,
               name: "users_community_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:community_documents) do
      modify :community_id,
             references(:communities,
               column: :id,
               name: "community_documents_community_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :uploaded_by_id,
             references(:users,
               column: :id,
               name: "community_documents_uploaded_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:communities) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :address, :map, null: false
      add :status, :text, null: false, default: "inactive"
      add :contact_email, :text
      add :contact_phone, :text
    end
  end

  def down do
    alter table(:communities) do
      remove :contact_phone
      remove :contact_email
      remove :status
      remove :address
      remove :name
      remove :created_at
    end

    drop constraint(:community_documents, "community_documents_community_id_fkey")

    drop constraint(:community_documents, "community_documents_uploaded_by_id_fkey")

    alter table(:community_documents) do
      modify :uploaded_by_id, :uuid
      modify :community_id, :uuid
    end

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop constraint(:users, "users_community_id_fkey")

    alter table(:users) do
      modify :community_id, :uuid
    end

    drop table(:communities)

    drop table(:community_documents)

    drop table(:tokens)

    drop table(:users)
  end
end
